/* global use, db */
// MongoDB Playground
// Use Ctrl+Space inside a snippet or a string literal to trigger completions.

const database = 'service-management2';
const collection = 'services';

use(database);

db.getCollection(collection).insertMany([
    {
        "guid": "e5b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Property Transfer",
        "serviceNameAr": "نقل الملكية",
        "code": "P-T01",
        "type": "Real Estate",
        "status": "inactive",
        "price": 1500.0,
        "descriptionAr": "خدمة لنقل ملكية العقار.",
        "descriptionEn": "Service for transferring property ownership.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "guid": "a37f5a65-1d5d-420d-9128-54675930cb71",
        "serviceName": "Vehicle Registration",
        "serviceNameAr": "تسجيل المركبات",
        "code": "V-R01",
        "type": "Transportation",
        "status": "active",
        "price": 500.0,
        "descriptionAr": "خدمة تسجيل المركبات.",
        "descriptionEn": "Registration service for vehicles.",
        "vattable": true,
        "vatValue": 10.0
    },
    {
        "guid": "c2d9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Legal Advisory",
        "serviceNameAr": "استشارات قانونية",
        "code": "L-A01",
        "type": "Services",
        "status": "inactive",
        "price": 3500.0,
        "descriptionAr": "خدمة استشارات قانونية.",
        "descriptionEn": "Legal advisory service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "guid": "d3e9f90e-4f6a-4c77-9057-1e8c92925ff9",
        "serviceName": "Market Research",
        "serviceNameAr": "أبحاث السوق",
        "code": "M-R01",
        "type": "Business",
        "status": "active",
        "price": 4000.0,
        "descriptionAr": "خدمة أبحاث السوق.",
        "descriptionEn": "Market research service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "guid": "e4b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Cybersecurity",
        "serviceNameAr": "الأمن السيبراني",
        "code": "C-S01",
        "type": "Technology",
        "status": "inactive",
        "price": 4500.0,
        "descriptionAr": "خدمة الأمن السيبراني.",
        "descriptionEn": "Cybersecurity service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "guid": "f5b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Project Management",
        "serviceNameAr": "إدارة المشاريع",
        "code": "P-M01",
        "type": "Business",
        "status": "active",
        "price": 5000.0,
        "descriptionAr": "خدمة إدارة المشاريع.",
        "descriptionEn": "Project management service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "guid": "g6b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Tax Consulting",
        "serviceNameAr": "استشارات ضريبية",
        "code": "T-C01",
        "type": "Finance",
        "status": "active",
        "price": 3000.0,
        "descriptionAr": "خدمة استشارات ضريبية.",
        "descriptionEn": "Tax consulting service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "h7b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Architectural Design",
        "serviceNameAr": "تصميم معماري",
        "code": "A-D01",
        "type": "Construction",
        "status": "active",
        "price": 6000.0,
        "descriptionAr": "خدمة تصميم معماري.",
        "descriptionEn": "Architectural design service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "i8b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Environmental Consulting",
        "serviceNameAr": "استشارات بيئية",
        "code": "E-C01",
        "type": "Environmental",
        "status": "active",
        "price": 3500.0,
        "descriptionAr": "خدمة استشارات بيئية.",
        "descriptionEn": "Environmental consulting service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "j9b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Logistics Management",
        "serviceNameAr": "إدارة اللوجستيات",
        "code": "L-M01",
        "type": "Transportation",
        "status": "active",
        "price": 4500.0,
        "descriptionAr": "خدمة إدارة اللوجستيات.",
        "descriptionEn": "Logistics management service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "k0b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Real Estate Valuation",
        "serviceNameAr": "تقييم العقارات",
        "code": "R-E01",
        "type": "Real Estate",
        "status": "active",
        "price": 5500.0,
        "descriptionAr": "خدمة تقييم العقارات.",
        "descriptionEn": "Real estate valuation service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "l1b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Insurance Brokerage",
        "serviceNameAr": "وساطة التأمين",
        "code": "I-B01",
        "type": "Insurance",
        "status": "active",
        "price": 2500.0,
        "descriptionAr": "خدمة وساطة التأمين.",
        "descriptionEn": "Insurance brokerage service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "b91d6f8e-3f9a-4328-99d1-7df8e5eaff5c",
        "serviceName": "Health Insurance",
        "serviceNameAr": "التأمين الصحي",
        "code": "H-I01",
        "type": "Insurance",
        "status": "active",
        "price": 3000.0,
        "descriptionAr": "خدمة التأمين الصحي.",
        "descriptionEn": "Health insurance service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "f3b1a4d0-8c6f-4c7d-bf2e-7f6f2d8aafeb",
        "serviceName": "Business Licensing",
        "serviceNameAr": "ترخيص الأعمال",
        "code": "B-L01",
        "type": "Licensing",
        "status": "inactive",
        "price": 2000.0,
        "descriptionAr": "خدمة ترخيص الأعمال.",
        "descriptionEn": "Service for business licensing.",
        "vattable": true,
        "vatValue": 12.5
    },
    {
        "id": "d4e9f90e-4f6a-4c77-9057-1e8c92925ff9",
        "serviceName": "Financial Consulting",
        "serviceNameAr": "استشارات مالية",
        "code": "F-C01",
        "type": "Finance",
        "status": "active",
        "price": 2500.0,
        "descriptionAr": "خدمة استشارات مالية.",
        "descriptionEn": "Financial consulting service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "e5b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Construction Permit",
        "serviceNameAr": "تصريح البناء",
        "code": "C-P01",
        "type": "Construction",
        "status": "active",
        "price": 5000.0,
        "descriptionAr": "خدمة تصريح البناء.",
        "descriptionEn": "Construction permit service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "a37f5a65-1d5d-420d-9128-54675930cb71",
        "serviceName": "Environmental Assessment",
        "serviceNameAr": "تقييم بيئي",
        "code": "E-A01",
        "type": "Environmental",
        "status": "active",
        "price": 3000.0,
        "descriptionAr": "خدمة تقييم بيئي.",
        "descriptionEn": "Environmental assessment service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "b91d6f8e-3f9a-4328-99d1-7df8e5eaff5c",
        "serviceName": "IT Support",
        "serviceNameAr": "دعم تكنولوجيا المعلومات",
        "code": "T-S01",
        "type": "Technology",
        "status": "inactive",
        "price": 1000.0,
        "descriptionAr": "خدمة دعم تكنولوجيا المعلومات.",
        "descriptionEn": "IT support service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "f3b1a4d0-8c6f-4c7d-bf2e-7f6f2d8aafeb",
        "serviceName": "Cleaning Services",
        "serviceNameAr": "خدمات التنظيف",
        "code": "S-C01",
        "type": "Services",
        "status": "active",
        "price": 800.0,
        "descriptionAr": "خدمة التنظيف.",
        "descriptionEn": "Cleaning services.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "e5b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Property Transfer",
        "serviceNameAr": "نقل الملكية",
        "code": "P-T01",
        "type": "Real Estate",
        "status": "inactive",
        "price": 1500.0,
        "descriptionAr": "خدمة لنقل ملكية العقار.",
        "descriptionEn": "Service for transferring property ownership.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "a37f5a65-1d5d-420d-9128-54675930cb71",
        "serviceName": "Vehicle Registration",
        "serviceNameAr": "تسجيل المركبات",
        "code": "V-R01",
        "type": "Transportation",
        "status": "active",
        "price": 500.0,
        "descriptionAr": "خدمة تسجيل المركبات.",
        "descriptionEn": "Registration service for vehicles.",
        "vattable": true,
        "vatValue": 10.0
    },
    {
        "id": "c2d9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Legal Advisory",
        "serviceNameAr": "استشارات قانونية",
        "code": "L-A01",
        "type": "Services",
        "status": "inactive",
        "price": 3500.0,
        "descriptionAr": "خدمة استشارات قانونية.",
        "descriptionEn": "Legal advisory service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "d3e9f90e-4f6a-4c77-9057-1e8c92925ff9",
        "serviceName": "Market Research",
        "serviceNameAr": "أبحاث السوق",
        "code": "M-R01",
        "type": "Business",
        "status": "active",
        "price": 4000.0,
        "descriptionAr": "خدمة أبحاث السوق.",
        "descriptionEn": "Market research service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "e4b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Cybersecurity",
        "serviceNameAr": "الأمن السيبراني",
        "code": "C-S01",
        "type": "Technology",
        "status": "inactive",
        "price": 4500.0,
        "descriptionAr": "خدمة الأمن السيبراني.",
        "descriptionEn": "Cybersecurity service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "f5b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Project Management",
        "serviceNameAr": "إدارة المشاريع",
        "code": "P-M01",
        "type": "Business",
        "status": "active",
        "price": 5000.0,
        "descriptionAr": "خدمة إدارة المشاريع.",
        "descriptionEn": "Project management service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "g6b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Tax Consulting",
        "serviceNameAr": "استشارات ضريبية",
        "code": "T-C01",
        "type": "Finance",
        "status": "active",
        "price": 3000.0,
        "descriptionAr": "خدمة استشارات ضريبية.",
        "descriptionEn": "Tax consulting service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "h7b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Architectural Design",
        "serviceNameAr": "تصميم معماري",
        "code": "A-D01",
        "type": "Construction",
        "status": "active",
        "price": 6000.0,
        "descriptionAr": "خدمة تصميم معماري.",
        "descriptionEn": "Architectural design service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "i8b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Environmental Consulting",
        "serviceNameAr": "استشارات بيئية",
        "code": "E-C01",
        "type": "Environmental",
        "status": "active",
        "price": 3500.0,
        "descriptionAr": "خدمة استشارات بيئية.",
        "descriptionEn": "Environmental consulting service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "j9b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Logistics Management",
        "serviceNameAr": "إدارة اللوجستيات",
        "code": "L-M01",
        "type": "Transportation",
        "status": "active",
        "price": 4500.0,
        "descriptionAr": "خدمة إدارة اللوجستيات.",
        "descriptionEn": "Logistics management service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "k0b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Real Estate Valuation",
        "serviceNameAr": "تقييم العقارات",
        "code": "R-E01",
        "type": "Real Estate",
        "status": "active",
        "price": 5500.0,
        "descriptionAr": "خدمة تقييم العقارات.",
        "descriptionEn": "Real estate valuation service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "l1b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Insurance Brokerage",
        "serviceNameAr": "وساطة التأمين",
        "code": "I-B01",
        "type": "Insurance",
        "status": "active",
        "price": 2500.0,
        "descriptionAr": "خدمة وساطة التأمين.",
        "descriptionEn": "Insurance brokerage service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "b91d6f8e-3f9a-4328-99d1-7df8e5eaff5c",
        "serviceName": "Health Insurance",
        "serviceNameAr": "التأمين الصحي",
        "code": "H-I01",
        "type": "Insurance",
        "status": "active",
        "price": 3000.0,
        "descriptionAr": "خدمة التأمين الصحي.",
        "descriptionEn": "Health insurance service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "f3b1a4d0-8c6f-4c7d-bf2e-7f6f2d8aafeb",
        "serviceName": "Business Licensing",
        "serviceNameAr": "ترخيص الأعمال",
        "code": "B-L01",
        "type": "Licensing",
        "status": "inactive",
        "price": 2000.0,
        "descriptionAr": "خدمة ترخيص الأعمال.",
        "descriptionEn": "Service for business licensing.",
        "vattable": true,
        "vatValue": 12.5
    },
    {
        "id": "d4e9f90e-4f6a-4c77-9057-1e8c92925ff9",
        "serviceName": "Financial Consulting",
        "serviceNameAr": "استشارات مالية",
        "code": "F-C01",
        "type": "Finance",
        "status": "active",
        "price": 2500.0,
        "descriptionAr": "خدمة استشارات مالية.",
        "descriptionEn": "Financial consulting service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "e5b9f90e-4f6a-4c77-9057-1e8c92925ff8",
        "serviceName": "Construction Permit",
        "serviceNameAr": "تصريح البناء",
        "code": "C-P01",
        "type": "Construction",
        "status": "active",
        "price": 5000.0,
        "descriptionAr": "خدمة تصريح البناء.",
        "descriptionEn": "Construction permit service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "a37f5a65-1d5d-420d-9128-54675930cb71",
        "serviceName": "Environmental Assessment",
        "serviceNameAr": "تقييم بيئي",
        "code": "E-A01",
        "type": "Environmental",
        "status": "active",
        "price": 3000.0,
        "descriptionAr": "خدمة تقييم بيئي.",
        "descriptionEn": "Environmental assessment service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "b91d6f8e-3f9a-4328-99d1-7df8e5eaff5c",
        "serviceName": "IT Support",
        "serviceNameAr": "دعم تكنولوجيا المعلومات",
        "code": "T-S01",
        "type": "Technology",
        "status": "inactive",
        "price": 1000.0,
        "descriptionAr": "خدمة دعم تكنولوجيا المعلومات.",
        "descriptionEn": "IT support service.",
        "vattable": true,
        "vatValue": 15.0
    },
    {
        "id": "f3b1a4d0-8c6f-4c7d-bf2e-7f6f2d8aafeb",
        "serviceName": "Cleaning Services",
        "serviceNameAr": "خدمات التنظيف",
        "code": "S-C01",
        "type": "Services",
        "status": "active",
        "price": 800.0,
        "descriptionAr": "خدمة التنظيف.",
        "descriptionEn": "Cleaning services.",
        "vattable": true,
        "vatValue": 15.0
    }
])
// More information on the `createCollection` command can be found at:
// https://www.mongodb.com/docs/manual/reference/method/db.createCollection/
